### ISSUE TITLE
Why MemoryError?

### ISSUE THREAD

**Issue by YYYYWD** [DavideNardone/PySMRS#1]
Hello!When I use the demo_video.py ，it always tell me "MemoryError". Can you help me?

sInd, repInd, C = smrs.smrs()
  self.C,_ = self.almLasso_mat_fun()
 mu1p = alpha1 * 1/self.computeLambda()
   T = np.linalg.norm(np.dot(self.data.T, tmp_mat),axis=1)
MemoryError

**Comment by DavideNardone** [comment]
Hello, sorry for the late reply. 
There was an error on line 61, where the Y matrix was not transposed. I fix it by adding the following instruction: **Y = np.transpose(np.asarray(Y))**.
Although this fix, it may happens that you still get this error which it's due to the fact the program cannot store a "big" internal matrix into the memory. The problem can be solved either by sub-sampling the initial matrix (which store each vectorized video frame) or by  adapting a specific block-strategy computing this matrix.
To solve the problem as fast as possible I would suggest to sub-sampling the video (at line 36 of demo_video.py) by 2x and then try to run the program again.
